apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    # Azure Key Vault name
    - name: vaultName
      value: "<AZURE_KEYVAULT_NAME>"  # Update with your Key Vault name
    
    # Azure AD tenant ID
    - name: tenantId
      value: "<AZURE_TENANT_ID>"  # Update with your Azure tenant ID
    
    # Azure AD client ID (service principal or managed identity)
    - name: clientId
      secretKeyRef:
        name: azure-keyvault-credentials
        key: clientId
    
    # Azure AD client secret (if using service principal)
    - name: clientSecret
      secretKeyRef:
        name: azure-keyvault-credentials
        key: clientSecret
    
    # Alternative: Use managed identity (recommended for AKS)
    # Remove clientId and clientSecret, and use:
    # - name: useManagedIdentity
    #   value: "true"
    # - name: azureClientId
    #   value: "<MANAGED_IDENTITY_CLIENT_ID>"

scopes:
  - backend
  - recurring-task-service
  - notification-service

